# Site settings
title:       oTree
email:       chris@otree.org
author:      chris@otree.org
description: "oTree : A software platform for social science experiments"
baseurl:     ""
url:         ""
url_docs:    "http://otree.readthedocs.org/en/latest/"
url_demo: "https://www.otreehub.com/projects/?featured=1"
url_download: "http://otree.readthedocs.org/en/latest/install.html"
url_tutorial: "http://otree.readthedocs.org/en/latest/tutorial/intro.html"
url_github: "https://github.com/oTree-org/oTree"
url_mailing_list: "https://groups.google.com/forum/#!forum/otree"

# Google analytics
google_analytics: UA-53910404-1

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: false


# Build settings
#markdown:     kramdown
markdown:     redcarpet
permalink:    pretty
paginate:     3
sass:
  compressed: true

